sonar.projectKey=isid-burgos
sonar.organization=isid-burgos
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.source=21
sonar.java.target=21

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=.github/**,k8s/**,docs/**,**/test/**

sonar.sourceEncoding=UTF-8
